//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udi.Comercio.Data.Infrastructure.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int PKProducto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int FkTipo { get; set; }
    
        public virtual Tipo Tipo { get; set; }
    }
}
